name: "Mathlib dependency updater"
description: "Updates your project to Mathlib releases and commits."
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Configure Lean
      uses: leanprover/lean-action@f807b338d95de7813c5c50d018f1c23c9b93b4ec # 2025-04-24
      with:
        auto-config: false
        use-github-cache: false
        use-mathlib-cache: false
        reinstall-transient-toolchain: true
    - name: "Check for Mathlib updates"
      run: node "${{ github.action_path }}/dist/index.js"
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
