on:
  workflow_dispatch:
jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      is-update-available: ${{ steps.check-for-updates.outputs.is-update-available }}
      new-tags: ${{ steps.check-for-updates.outputs.new-tags }}
    steps:
      - name: Run the action
        id: check-for-updates
        uses: leanprover-community/mathlib-update-action@main
  do-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.is-update-available }}
    strategy:
      fail-fast: false # Let other jobs continue if one of the jobs in the matrix errors.
      max-parallel: 1 # Ensures that the PRs/issues are created in order.
      matrix:
        tag: ${{ fromJSON(needs.check-for-updates.outputs.new-tags) }}
    steps:
      - name: Run the action
        id: create-update
        uses: leanprover-community/mathlib-update-action/do-update@main
        with:
          tag: ${{ matrix.tag }}
