on:
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run the action
        uses: Vierkantor/lean-update-tester@main
